version: "3.8"

services:
  mysql:
    container_name: mysql
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "3001:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
  # backend:
  #   container_name: fastapi
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - mysql
  #   environment:
  #     - FASTAPI_ENV=docker

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"

volumes:
  mysql_data: